#!/usr/bin/env python3
"""Build and synchronize Spark Push's self-contained Skills into Hermes."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import sys
import tempfile
from datetime import datetime
from pathlib import Path, PurePosixPath


SKILL_NAMES = ("spark-push-agent", "spark-push-knowledge")
BUNDLE_NAME = "spark-push-agent.yaml"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument(
        "--check", action="store_true", help="compare the installed package with the repository"
    )
    action.add_argument(
        "--install", action="store_true", help="install a missing package or refresh it"
    )
    parser.add_argument(
        "--replace",
        action="store_true",
        help="replace a changed install after moving the old one to a timestamped backup",
    )
    parser.add_argument(
        "--hermes-home",
        type=Path,
        help="Hermes data directory; defaults to HERMES_HOME, /mnt/f/hermes, or ~/.hermes",
    )
    return parser.parse_args()


def default_hermes_home() -> Path:
    configured = os.environ.get("HERMES_HOME", "").strip()
    if configured:
        return Path(configured).expanduser()
    windows_home = Path("/mnt/f/hermes")
    if (windows_home / "config.yaml").is_file() and (windows_home / "skills").is_dir():
        return windows_home
    return Path.home() / ".hermes"


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def read_manifest(repo_root: Path) -> list[dict]:
    path = repo_root / "cannbot" / "knowledge-sources.json"
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"cannot read {path}: {exc}") from exc
    sources = data.get("sources")
    if data.get("schema_version") != 1 or not isinstance(sources, list) or not sources:
        raise ValueError(f"invalid knowledge manifest: {path}")
    return sources


def safe_source(repo_root: Path, value: object) -> tuple[str, Path]:
    if not isinstance(value, str):
        raise ValueError("knowledge source path must be a string")
    relative = PurePosixPath(value)
    if not value or relative.is_absolute() or ".." in relative.parts:
        raise ValueError(f"unsafe knowledge source path: {value!r}")
    resolved = (repo_root / Path(*relative.parts)).resolve()
    try:
        resolved.relative_to(repo_root.resolve())
    except ValueError as exc:
        raise ValueError(f"knowledge source escapes repository: {value}") from exc
    if not resolved.is_file():
        raise ValueError(f"knowledge source does not exist: {value}")
    return relative.as_posix(), resolved


def collect_static_skill(skill_dir: Path) -> dict[str, bytes]:
    files: dict[str, bytes] = {}
    for path in sorted(skill_dir.rglob("*")):
        if not path.is_file():
            continue
        relative = path.relative_to(skill_dir).as_posix()
        parts = PurePosixPath(relative).parts
        if parts and parts[0] == "evals":
            continue
        if relative == "references/installed-source-map.md":
            continue
        if parts[:2] == ("references", "sources"):
            continue
        files[relative] = path.read_bytes()
    if "SKILL.md" not in files:
        raise ValueError(f"missing SKILL.md in {skill_dir}")
    return files


def build_source_map(rows: list[tuple[str, str, str, str, str]]) -> bytes:
    lines = [
        "# Installed source map",
        "",
        "This file is generated by `cannbot/scripts/sync_hermes_skills.py`.",
        "The package is a point-in-time snapshot; original paths remain the citation names.",
        "",
        "| Source ID | Authority | Original path | Installed path | SHA-256 |",
        "|---|---|---|---|---|",
    ]
    for source_id, authority, original, installed, sha256 in rows:
        lines.append(
            f"| `{source_id}` | `{authority}` | `{original}` | `{installed}` | `{sha256}` |"
        )
    lines.extend(
        [
            "",
            "Use `skill_view(\"spark-push-knowledge\", file_path=\"<Installed path>\")` ",
            "to load a source. If the live repository is available, prefer live code when it differs ",
            "from this snapshot and run the sync script again.",
            "",
        ]
    )
    return "\n".join(lines).encode("utf-8")


def build_skill_packages(repo_root: Path) -> dict[str, dict[str, bytes]]:
    packages: dict[str, dict[str, bytes]] = {}
    for name in SKILL_NAMES:
        skill_dir = repo_root / "cannbot" / "skills" / name
        if not skill_dir.is_dir():
            raise ValueError(f"missing skill directory: {skill_dir}")
        packages[name] = collect_static_skill(skill_dir)

    sources = read_manifest(repo_root)
    knowledge = packages["spark-push-knowledge"]
    manifest_path = repo_root / "cannbot" / "knowledge-sources.json"
    knowledge["references/knowledge-sources.json"] = manifest_path.read_bytes()
    rows: list[tuple[str, str, str, str, str]] = []
    seen_ids: set[str] = set()
    seen_paths: set[str] = set()
    for source in sources:
        source_id = source.get("id")
        authority = source.get("authority")
        if not isinstance(source_id, str) or not source_id or source_id in seen_ids:
            raise ValueError(f"invalid or duplicate knowledge source id: {source_id!r}")
        if not isinstance(authority, str) or not authority:
            raise ValueError(f"invalid authority for knowledge source {source_id}")
        original, source_path = safe_source(repo_root, source.get("path"))
        if original in seen_paths:
            raise ValueError(f"duplicate knowledge source path: {original}")
        seen_ids.add(source_id)
        seen_paths.add(original)
        installed = f"references/sources/{original}"
        content = source_path.read_bytes()
        knowledge[installed] = content
        rows.append((source_id, authority, original, installed, digest(content)))
    knowledge["references/installed-source-map.md"] = build_source_map(rows)
    return packages


def tree_files(root: Path) -> dict[str, bytes]:
    if not root.is_dir():
        return {}
    return {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def package_state(target: Path, expected: dict[str, bytes]) -> str:
    if not target.exists():
        return "missing"
    if not target.is_dir():
        return "wrong-type"
    return "current" if tree_files(target) == expected else "changed"


def file_state(target: Path, expected: bytes) -> str:
    if not target.exists():
        return "missing"
    if not target.is_file():
        return "wrong-type"
    return "current" if target.read_bytes() == expected else "changed"


def backup_path(target: Path) -> Path:
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    candidate = target.with_name(f"{target.name}.backup-{stamp}")
    counter = 1
    while candidate.exists():
        candidate = target.with_name(f"{target.name}.backup-{stamp}-{counter}")
        counter += 1
    return candidate


def install_directory(target: Path, expected: dict[str, bytes], replace: bool) -> str:
    state = package_state(target, expected)
    if state == "current":
        return "unchanged"
    if state != "missing" and not replace:
        raise RuntimeError(f"refusing to overwrite {state} install: {target}; use --replace")

    target.parent.mkdir(parents=True, exist_ok=True)
    backup: Path | None = None
    if target.exists():
        backup = backup_path(target)
        target.rename(backup)

    temp_root = Path(tempfile.mkdtemp(prefix=f".{target.name}.install-", dir=target.parent))
    stage = temp_root / target.name
    try:
        for relative, content in expected.items():
            output = stage / Path(*PurePosixPath(relative).parts)
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_bytes(content)
        stage.replace(target)
    except Exception:
        if backup is not None and backup.exists() and not target.exists():
            backup.rename(target)
        raise
    finally:
        shutil.rmtree(temp_root, ignore_errors=True)
    return f"installed (backup: {backup})" if backup else "installed"


def install_file(target: Path, expected: bytes, replace: bool) -> str:
    state = file_state(target, expected)
    if state == "current":
        return "unchanged"
    if state != "missing" and not replace:
        raise RuntimeError(f"refusing to overwrite {state} install: {target}; use --replace")

    target.parent.mkdir(parents=True, exist_ok=True)
    backup: Path | None = None
    if target.exists():
        backup = backup_path(target)
        target.rename(backup)
    fd, temp_name = tempfile.mkstemp(prefix=f".{target.name}.install-", dir=target.parent)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(expected)
        Path(temp_name).replace(target)
    except Exception:
        Path(temp_name).unlink(missing_ok=True)
        if backup is not None and backup.exists() and not target.exists():
            backup.rename(target)
        raise
    return f"installed (backup: {backup})" if backup else "installed"


def main() -> int:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[2]
    hermes_home = (args.hermes_home or default_hermes_home()).expanduser().resolve()
    try:
        packages = build_skill_packages(repo_root)
        bundle_source = repo_root / "cannbot" / "hermes" / BUNDLE_NAME
        bundle = bundle_source.read_bytes()
    except (OSError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    targets = {
        name: hermes_home / "skills" / name
        for name in SKILL_NAMES
    }
    bundle_target = hermes_home / "skill-bundles" / BUNDLE_NAME

    if args.check:
        ok = True
        for name, target in targets.items():
            state = package_state(target, packages[name])
            print(f"{name}: {state} ({target})")
            ok = ok and state == "current"
        state = file_state(bundle_target, bundle)
        print(f"bundle: {state} ({bundle_target})")
        ok = ok and state == "current"
        return 0 if ok else 1

    try:
        for name, target in targets.items():
            result = install_directory(target, packages[name], args.replace)
            print(f"{name}: {result} ({target})")
        result = install_file(bundle_target, bundle, args.replace)
        print(f"bundle: {result} ({bundle_target})")
    except (OSError, RuntimeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    print("Hermes Skill 同步完成。请在 Hermes CLI 执行 /reload-skills，或重启 Gateway/API Server。")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
